/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SparePartsRouteImport } from './routes/spare-parts'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShipmentsRouteImport } from './routes/shipments'
import { Route as PendingAnalysisRouteImport } from './routes/pending-analysis'
import { Route as MonthlyTrendsRouteImport } from './routes/monthly-trends'
import { Route as DeepInsightsRouteImport } from './routes/deep-insights'
import { Route as DailyOperationsRouteImport } from './routes/daily-operations'
import { Route as CallCenterRouteImport } from './routes/call-center'
import { Route as BranchComparisonRouteImport } from './routes/branch-comparison'
import { Route as AscPerformanceRouteImport } from './routes/asc-performance'
import { Route as IndexRouteImport } from './routes/index'

const SparePartsRoute = SparePartsRouteImport.update({
  id: '/spare-parts',
  path: '/spare-parts',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsRoute = ShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingAnalysisRoute = PendingAnalysisRouteImport.update({
  id: '/pending-analysis',
  path: '/pending-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const MonthlyTrendsRoute = MonthlyTrendsRouteImport.update({
  id: '/monthly-trends',
  path: '/monthly-trends',
  getParentRoute: () => rootRouteImport,
} as any)
const DeepInsightsRoute = DeepInsightsRouteImport.update({
  id: '/deep-insights',
  path: '/deep-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyOperationsRoute = DailyOperationsRouteImport.update({
  id: '/daily-operations',
  path: '/daily-operations',
  getParentRoute: () => rootRouteImport,
} as any)
const CallCenterRoute = CallCenterRouteImport.update({
  id: '/call-center',
  path: '/call-center',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchComparisonRoute = BranchComparisonRouteImport.update({
  id: '/branch-comparison',
  path: '/branch-comparison',
  getParentRoute: () => rootRouteImport,
} as any)
const AscPerformanceRoute = AscPerformanceRouteImport.update({
  id: '/asc-performance',
  path: '/asc-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asc-performance': typeof AscPerformanceRoute
  '/branch-comparison': typeof BranchComparisonRoute
  '/call-center': typeof CallCenterRoute
  '/daily-operations': typeof DailyOperationsRoute
  '/deep-insights': typeof DeepInsightsRoute
  '/monthly-trends': typeof MonthlyTrendsRoute
  '/pending-analysis': typeof PendingAnalysisRoute
  '/shipments': typeof ShipmentsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spare-parts': typeof SparePartsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asc-performance': typeof AscPerformanceRoute
  '/branch-comparison': typeof BranchComparisonRoute
  '/call-center': typeof CallCenterRoute
  '/daily-operations': typeof DailyOperationsRoute
  '/deep-insights': typeof DeepInsightsRoute
  '/monthly-trends': typeof MonthlyTrendsRoute
  '/pending-analysis': typeof PendingAnalysisRoute
  '/shipments': typeof ShipmentsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spare-parts': typeof SparePartsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asc-performance': typeof AscPerformanceRoute
  '/branch-comparison': typeof BranchComparisonRoute
  '/call-center': typeof CallCenterRoute
  '/daily-operations': typeof DailyOperationsRoute
  '/deep-insights': typeof DeepInsightsRoute
  '/monthly-trends': typeof MonthlyTrendsRoute
  '/pending-analysis': typeof PendingAnalysisRoute
  '/shipments': typeof ShipmentsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spare-parts': typeof SparePartsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asc-performance'
    | '/branch-comparison'
    | '/call-center'
    | '/daily-operations'
    | '/deep-insights'
    | '/monthly-trends'
    | '/pending-analysis'
    | '/shipments'
    | '/sitemap.xml'
    | '/spare-parts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asc-performance'
    | '/branch-comparison'
    | '/call-center'
    | '/daily-operations'
    | '/deep-insights'
    | '/monthly-trends'
    | '/pending-analysis'
    | '/shipments'
    | '/sitemap.xml'
    | '/spare-parts'
  id:
    | '__root__'
    | '/'
    | '/asc-performance'
    | '/branch-comparison'
    | '/call-center'
    | '/daily-operations'
    | '/deep-insights'
    | '/monthly-trends'
    | '/pending-analysis'
    | '/shipments'
    | '/sitemap.xml'
    | '/spare-parts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AscPerformanceRoute: typeof AscPerformanceRoute
  BranchComparisonRoute: typeof BranchComparisonRoute
  CallCenterRoute: typeof CallCenterRoute
  DailyOperationsRoute: typeof DailyOperationsRoute
  DeepInsightsRoute: typeof DeepInsightsRoute
  MonthlyTrendsRoute: typeof MonthlyTrendsRoute
  PendingAnalysisRoute: typeof PendingAnalysisRoute
  ShipmentsRoute: typeof ShipmentsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SparePartsRoute: typeof SparePartsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spare-parts': {
      id: '/spare-parts'
      path: '/spare-parts'
      fullPath: '/spare-parts'
      preLoaderRoute: typeof SparePartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments': {
      id: '/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof ShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-analysis': {
      id: '/pending-analysis'
      path: '/pending-analysis'
      fullPath: '/pending-analysis'
      preLoaderRoute: typeof PendingAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monthly-trends': {
      id: '/monthly-trends'
      path: '/monthly-trends'
      fullPath: '/monthly-trends'
      preLoaderRoute: typeof MonthlyTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deep-insights': {
      id: '/deep-insights'
      path: '/deep-insights'
      fullPath: '/deep-insights'
      preLoaderRoute: typeof DeepInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-operations': {
      id: '/daily-operations'
      path: '/daily-operations'
      fullPath: '/daily-operations'
      preLoaderRoute: typeof DailyOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-center': {
      id: '/call-center'
      path: '/call-center'
      fullPath: '/call-center'
      preLoaderRoute: typeof CallCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch-comparison': {
      id: '/branch-comparison'
      path: '/branch-comparison'
      fullPath: '/branch-comparison'
      preLoaderRoute: typeof BranchComparisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asc-performance': {
      id: '/asc-performance'
      path: '/asc-performance'
      fullPath: '/asc-performance'
      preLoaderRoute: typeof AscPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AscPerformanceRoute: AscPerformanceRoute,
  BranchComparisonRoute: BranchComparisonRoute,
  CallCenterRoute: CallCenterRoute,
  DailyOperationsRoute: DailyOperationsRoute,
  DeepInsightsRoute: DeepInsightsRoute,
  MonthlyTrendsRoute: MonthlyTrendsRoute,
  PendingAnalysisRoute: PendingAnalysisRoute,
  ShipmentsRoute: ShipmentsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SparePartsRoute: SparePartsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
